trigger: none 

jobs:
- job: build_knative_serving
  pool:
    vmImage: 'ubuntu-latest'
  workspace:
    clean: all
  variables:
    GOPATH: $(System.DefaultWorkingDirectory)/go
    repo.path: $(GOPATH)/src/knative.dev/serving
  steps:
  # - bash: |
  #     git clone -b $(checkout.branch) $(checkout.repo) $(repo.path) && \
  #     mkdir -p $(repo.path)/_output/release-images/amd64
  #   displayName: Checkout $(checkout.repo) @ $(checkout.branch)
  - bash: |
      go get github.com/google/ko/cmd/ko
    displayName: Get KO
    # workingDirectory: $(repo.path)
  - bash: |
      wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
      tar -xf azcopy.tar.gz
      cp azcopy_linux_amd64_10.2.1/azcopy ${Agent.ToolsDirectory}
      chmod +x ${Agent.ToolsDirectory}/azcopy
    displayName: Get AZCOPY
    # workingDirectory: $(repo.path)
  - bash: |
      ./hack/release.sh --test-args "--unit-tests" --release-acr rakelkartest --release-azblob https://kntestblob.blob.core.windows.net/knt1 --publish --tag-release
      docker save -o $(repo.path)/_output/release-images/amd64/metrics-server-amd64.tar ${PREFIX}/metrics-server-amd64:${VERSION}
      rm -rf $(repo.path)/vendor
    displayName: Build image and save to $(repo.path)/_output/release-images/amd64
    # workingDirectory: $(repo.path)
    env:
      PREFIX: $(registry.url)/$(registry.repo)
      VERSION: $(checkout.branch)
