trigger: none 

jobs:
- job: build_knative_serving
  pool:
    vmImage: 'ubuntu-latest'
  workspace:
    clean: all
  variables:
    GOPATH: $(System.DefaultWorkingDirectory)/go
    repo.path: $(GOPATH)/src/knative.dev/serving
  steps:
  - task: GoTool@0
    displayName: 'Use Go 1.11.12'
    inputs:
      version: '1.11.12'
      goPath: '$(GOPATH)'
      goBin: '$(GOBIN)'
  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
      go env
    displayName: 'Set up the Go workspace'

  - task: Bash@3
    displayName: 'Setup GO tools'
    inputs:
      targetType: filePath
      filePath: './hack/go-tools-setup.sh'
  - bash: |
      go get github.com/google/ko/cmd/ko
    displayName: Get KO
    # workingDirectory: $(repo.path)
  - bash: |
      wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
      tar -xf azcopy.tar.gz
      cp azcopy_linux_amd64_10.2.1/azcopy ${AGENT_TOOLSDIRECTORY}
      chmod +x ${AGENT_TOOLSDIRECTORY}/azcopy
    displayName: Get AZCOPY
    # workingDirectory: $(repo.path)
  - script: |
      go get -v -t -d ./...
      if [ -f Gopkg.toml ]; then
          echo "dep ensure"
      fi
    #workingDirectory: '$(controllerPath)'
    displayName: 'Get dependencies'
  - bash: |
      ./hack/release.sh --test-args "--unit-tests" --release-acr rakelkartest --release-azblob https://kntestblob.blob.core.windows.net/knt1 --publish --tag-release
      docker save -o $(repo.path)/_output/release-images/amd64/metrics-server-amd64.tar ${PREFIX}/metrics-server-amd64:${VERSION}
      rm -rf $(repo.path)/vendor
    displayName: Build image and save to $(repo.path)/_output/release-images/amd64
    # workingDirectory: $(repo.path)
    env:
      PREFIX: $(registry.url)/$(registry.repo)
      VERSION: $(checkout.branch)
